### PR TITLE
Swift 3.0 fixes

### PR DESCRIPTION
**Pull request by bootstraponline**
Swift 3 fixes from Xcode 8.2.1 migrator.

### CODE REVIEW

**Comment by tirodkar** [comment]
LGTM. Waiting on the CI.

**Comment by tirodkar** [comment]
QQ - will this work in older Xcode versions? What if a user has Xcode 8.0 or 8.1?

**Comment by bootstraponline** [comment]
> QQ - will this work in older Xcode versions? What if a user has Xcode 8.0 or 8.1?

I think it will break them. I don't know for sure though.

**Comment by tirodkar** [comment]
Cool. Let's wait for the CI to run and see the result. In case there's a failure, we might have to move this to a new EarlGrey.swift version and make changes to the Travis Xcode versions for CI checks, which currently does not have 8.2.1 support.

**Comment by khandpur** [comment]
Travis Swift test fails: https://travis-ci.org/google/EarlGrey/jobs/189054172

**Comment by bootstraponline** [comment]
How do we want to version this? It looks like Xcode 8.2.1 is still considered `Swift 3`

**Comment by bootstraponline** [comment]
I reverted the label changes. I expect Travis to pass now.

**Comment by bootstraponline** [comment]
Thoughts on moving all the `public` access to `open`? Right now I just have the ones that Xcode complained about.

- https://github.com/apple/swift-evolution/blob/master/proposals/0117-non-public-subclassable-by-default.md

**Comment by tirodkar** [comment]
We should move them all to open as per the swift-evolution suggestion.

**Pull request merged**
