### PR TITLE
fix comment line

### PR DESCRIPTION
**Pull request by KazuCocoa**
[ci skip]

### CODE REVIEW

**Comment by KazuCocoa** [comment]
I signed 👌

**Comment by tirodkar** [comment]
Add [ci skip] to your commit and I'll merge this.

**Comment by KazuCocoa** [comment]
Ok, I'll add [ci skip] in my commit message later.

**Comment by tirodkar** [comment]
@KazuCocoa, I guess it's fine for now. Next time, please add `[ci skip]` in the git commit that you push if it doesn't have a code change. As in 

`git commit -m "fix comment line [ci skip]"`

Thanks a lot.

**Comment by KazuCocoa** [comment]
Thanks you so much !
I just send this via browser...

**Pull request merged**
