### PR TITLE
Experimental Changes

### PR DESCRIPTION
**Pull request by axi0mX**
Experimental changes.

### CODE REVIEW

**Comment by bootstraponline** [comment]
> c) other apps, such as Safari

Does that work on real devices as well?

**Comment by axi0mX** [comment]
@bootstraponline Yes! You can control the entire device, for now. 

Allowing control outside of the app's sandbox is a potential security issue, so it's possible Apple will block it in the future, but for now it works, I tested it on iOS 9.3.

**Comment by bootstraponline** [comment]
The PR was closed? :(

**Comment by khandpur** [comment]
We discussed a better design offline with the author hence decided to put this on hold.

**Pull request closed without merging**
