### PR TITLE
EarlGrey 2.0 | Add a Universal Build Framework Script. This can be added to projects to build any EarlGrey components as frameworks

### PR DESCRIPTION
**Pull request by tirodkar**
…

### CODE REVIEW

**Comment by tirodkar** [comment]
@bootstraponline please check the dsym update.

**Comment by bootstraponline** [comment]
looks great!

**Comment by bootstraponline** [comment]
I think we need another script to actually build the framework. See my original PR:
https://github.com/google/EarlGrey/pull/746

It'd probably look something like this:

```bash
#!/bin/bash

export PROJECT_FILE_PATH="../EarlGrey.xcodeproj"
export PRODUCT_NAME="EarlGrey"
export BUILT_PRODUCTS_DIR=`dirname "$BASH_SOURCE"`
export SDK_NAME="iphoneos 11.2"
export TARGET_NAME="EarlGrey"
export CONFIGURATION="Release"
export BUILD_DIR="$HOME/Library/Developer/Xcode/DerivedData"
export OBJROOT="$BUILD_DIR"
export BUILD_ROOT="$BUILD_DIR"
export SYMROOT="$BUILD_DIR"
export ACTION="build"

( exec "./build_universal_dynamic_framework.sh" )
```

There are a bunch of vars that I'm not sure about. The above doesn't execute successfully. If a working version is added then I'll be able to replace my existing build script.

**Comment by tirodkar** [comment]
Can you send the error trace, if any?

**Comment by bootstraponline** [comment]
error:

```
./universal_earlgrey.sh
Could not find platform name from build products directory:  .
xcodebuild: error: SDK "iphonesimulator11.2" cannot be located.
```

**Pull request closed without merging**
