### PR TITLE
Update error logging and reporting format

### PR DESCRIPTION
**Pull request by wuhao5**
https://github.com/google/EarlGrey/issues/392

@phsong-google @khandpur @sid-github @tirodkar

### CODE REVIEW

**Comment by khandpur** [comment]
This is failing most Travis tests:
https://travis-ci.org/google/EarlGrey/builds/193839416

**Comment by khandpur** [comment]
Fixes #392

**Comment by wuhao5** [comment]
FYI, the builds started passing now, with some flaky tests.

**Comment by wuhao5** [comment]
this one should be good to go.

**Pull request merged**
