### PR TITLE
Changed CFBundlePackageType in EarlGrey-Info.plist to FMWK

### PR DESCRIPTION
**Pull request by ninjazoete**
Changed CFBundlePackageType to be compatible with Carthage.

### CODE REVIEW

**Comment by ninjazoete** [comment]
I signed it!

**Comment by tirodkar** [comment]
I don't think the contents.xcworkspacedata file is needed.

**Comment by ninjazoete** [comment]
You are right. Should I create another merge request or can I discard the second file somehow here?

**Comment by tirodkar** [comment]
You could remove the file and amend your current commit. We prefer having one commit per pull request. Also, it seems like the CLA wasn't correctly signed.

**Pull request closed without merging**
