### PR TITLE
Update RVM to 2.3.0 as it's failing to update

### PR DESCRIPTION
**Pull request by khandpur**
https://travis-ci.org/google/EarlGrey/jobs/471151306:
```
Updating rubygems-update
ERROR:  Error installing rubygems-update:
	rubygems-update requires Ruby version >= 2.3.0.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
The command "gem update --system" failed and exited with 1 during .
```

### CODE REVIEW

**Comment by wuhao5** [comment]
The ruby issue should be fixed, not sure about the other failure, shouldn't be related?

**Comment by khandpur** [comment]
Right. The unit test failures are known. Waiting on FTR to complete to see what other failures there are.

**Comment by tirodkar** [comment]
Yeah, we've seen the other failure before with the Unit tests. There seems to be a blacklisting URL issue that we've seen on Travis but I wasn't able to reproduce locally. This cl is good to go.

**Comment by khandpur** [comment]
Functional failures are also known failures. This is ready to merge.

**Pull request merged**
