### PR TITLE
Internal to external sync

### PR DESCRIPTION
**Pull request by wuhao5**

### CODE REVIEW

**Comment by wuhao5** [comment]
@sid-github and @khandpur are the original author for those two commits, we should be good to merge it. please review and let me know!

**Comment by tirodkar** [comment]
The author is @sskhandp for the first commit.

**Comment by sskhandp** [comment]
I've signed it.

**Comment by wuhao5** [comment]
looks like cla/google won't verify it but leave the authors to consent, I think we are good wrt CLA.

**Comment by wuhao5** [comment]
fixed the wrong commit author.

**Comment by wuhao5** [comment]
looks like the broken ones are fixed after the travis change, waiting for others to complete.

**Pull request merged**
