### PR TITLE
Internal to external sync - 09/08/2016

### PR DESCRIPTION
**Pull request by tirodkar**
Additions:

* A grey_selected() Matcher to check if a UIControl is selected and add tests.
* Add GREYStringDescription Unit Tests
* Fix formatting and comment issues.

### CODE REVIEW

**Comment by bootstraponline** [comment]
The new matcher isn't included in the cheatsheet HTML?

**Comment by tirodkar** [comment]
I was planning to send that along with the CHANGELOG.md etc.

**Comment by bootstraponline** [comment]
Ok, sounds good.

**Comment by tirodkar** [comment]
Cheatsheet updated at https://github.com/google/EarlGrey/pull/261

**Comment by khandpur** [comment]
Two unit tests not related to this PR are failing. See
https://travis-ci.org/google/EarlGrey/jobs/158620389
https://travis-ci.org/google/EarlGrey/jobs/158620384

We should file bugs for them. LGTM otherwise.

**Pull request merged**
