### PR TITLE
Update api.md

### PR DESCRIPTION
**Pull request by hillchan31**
fix the code for matching brackets

### CODE REVIEW

**Comment by hillchan31** [comment]
I signed it!

**Comment by khandpur** [comment]
Thanks @hillchan31 !

**Comment by hillchan31** [comment]
@khandpur 
My pleasure.
Recently, I am translating docs about EarlGrey into Chinese.
Does the EarlGrey need Chinese docs?

**Comment by khandpur** [comment]
That would be pretty useful. We could either check it in or link it off of our guide.

**Pull request merged**
