### PR TITLE
Merging multiple -if/fi into single if/elif/fi

### PR DESCRIPTION
**Pull request by khandpur**
* Introducing another env var for unit tests
* Making travis build not fail if one of fi statements fails (not the command that's supposed to run inside it)

### CODE REVIEW

**Comment by bootstraponline** [comment]
👍

**Comment by bootstraponline** [comment]
FYI this is why I used an external script. 😄

**Comment by bootstraponline** [comment]
LGTM.

**Comment by khandpur** [comment]
@bootstraponline @tirodkar @sid-github 
This is good to go. Please do another pass.

**Comment by bootstraponline** [comment]
Looks good.

**Comment by sid-github** [comment]
LGTM (PR comments dont mention the changes you made to unittest proj file, consider adding them).

**Comment by khandpur** [comment]
@sid-github I reverted the changes to unit test. @tirodkar will be sending new PR with all those changes

**Comment by khandpur** [comment]
wait on travis results for the latest commit:
https://travis-ci.org/google/EarlGrey/builds/140962893

**Pull request merged**
