### PR TITLE
Fix for Missing Swift 3.2 and Swift 4.0 Support Issue #580

### PR DESCRIPTION
**Pull request by mettieDie**
Created Swift 3.2 and Swift 4.0 Folders to ensure building Earlgrey for Projects using Swift 3.2 and Swift 4.0

### CODE REVIEW

**Comment by mettieDie** [comment]
I signed it!

**Comment by mettieDie** [comment]
I signed it!

**Comment by wuhao5** [comment]
If they are the same, can we make a change here: 
https://github.com/google/EarlGrey/blob/master/gem/lib/earlgrey/configure_earlgrey.rb#L381

so when the swift file is not found, use the backup 3.0 version?

**Comment by mettieDie** [comment]
Yes they are the same. We can use the Swift 3.0 Version. I can implement this tomorrow.

**Comment by tirodkar** [comment]
@bootstraponline Is it time for us to deprecate he 3.0 and 2.3 files for these? At least the 2.3 one?

**Comment by bootstraponline** [comment]
> @bootstraponline Is it time for us to deprecate he 3.0 and 2.3 files for these? At least the 2.3 one?

I think so. We should probably only support the latest stable Xcode release. Swift is changing too rapidly to support all the versions forever.

**Comment by khandpur** [comment]
@tirodkar @wuhao5 Could we merge this if it's good to go?

**Comment by wuhao5** [comment]
I think the decision is to not add another swift file but have gem to handle it.

**Comment by tirodkar** [comment]
Hello, I thought we were waiting on the additions to the gem here. Is that to be done in a separate PR?

**Comment by wuhao5** [comment]
closing in favor of #591

**Pull request closed without merging**
