### PR TITLE
Add Swift action example

### LINKED ISSUE #111: Custom action Swift example
It'd be nice to have a simple example of how to do a custom action using Swift.

### PR DESCRIPTION
**Pull request by bootstraponline**
Fix #111

### CODE REVIEW

**Comment by tirodkar** [comment]
I've got a different action that I'm adding to the basic views test here. Also, could you create a local GREYActionBlock and use it instead of returning it directly?

**Comment by bootstraponline** [comment]
> I've got a different action that I'm adding to the basic views test here.

Is that suppose to be linked?

**Comment by bootstraponline** [comment]
> Also, could you create a local GREYActionBlock and use it instead of returning it directly?

So remove the wrapper function and just keep `GREYActionBlock.actionWithName`? Or keep the wrapper & add an example usage?

**Comment by tirodkar** [comment]
Remove the wrapper function. Just have the block.

I'd think it would be nicer to see an example that is also in a test, so it can be immediately referenced.

**Comment by bootstraponline** [comment]
> I'd think it would be nicer to see an example that is also in a test, so it can be immediately referenced.

I agree. I added this one to `FTRSwiftTests.swift`. Let me know what you think.

**Comment by bootstraponline** [comment]
closing in favor of tirodkar's upcoming PR.

**Pull request closed without merging**
