### PR TITLE
Add nullability macros to all EarlGrey headers.

### PR DESCRIPTION
**Pull request by tirodkar**

### CODE REVIEW

**Comment by khandpur** [comment]
Unit tests fail:
https://travis-ci.org/google/EarlGrey/jobs/351569357

**Comment by khandpur** [comment]
Full error:
```
/Users/travis/build/google/EarlGrey/Tests/UnitTests/Sources/GREYFailureFormatterTest.m:38:45: null passed to a callee that requires a non-null argument [-Werror,-Wnonnull]
  NSString *failure = [GREYFailureFormatter formatFailureForTestCase:currentTestCase
```

Will merge once that's fixed.

**Comment by tirodkar** [comment]
Updated Project. PTAL.

**Comment by khandpur** [comment]
Still see a lot of failures: https://travis-ci.org/google/EarlGrey/builds/357608543?utm_source=github_status&utm_medium=notification

**Comment by khandpur** [comment]
Exact error:
> No such file or directory: '/Users/travis/build/google/EarlGrey/EarlGrey/EarlGrey.m'

**Pull request merged**
