### PR TITLE
Add script to build universal framework

### LINKED ISSUE #745: Universal Static Library Script
It'd be nice to have a script that generates a universal static library for EarlGrey. Then when EarlGrey is used in CI, the dependency doesn't have to be recompiled.

- https://github.com/AudioKit/AudioKit/blob/master/Frameworks/build_frameworks.sh
- https://github.com/KeepSafe/ObjectiveRocks/blob/frameworks/build_universal_framework.sh
- http://devcenter.bitrise.io/docs/should-i-commit-my-dependencies-into-my-repository

### PR DESCRIPTION
**Pull request by bootstraponline**
Fix #745

### CODE REVIEW

**Comment by tirodkar** [comment]
If you add this to `EarlGrey.xcodeproj`, will everything work fine?

**Comment by bootstraponline** [comment]
Would you prefer this be part of the xcode project? It's possible to add a shell script.

The problem is it'll slow down the builds for users that don't need a universal framework. Typically the pattern I've seen is to add an external export script.

**Comment by tirodkar** [comment]
That sounds good. LG from my side.

**Comment by khandpur** [comment]
@tirodkar we have something like this we use internally. Why not open source that and let Matt add his changes to that? That way we use one single script to generate framework that we ship to cocoapod users?

**Comment by bootstraponline** [comment]
That sounds awesome.

**Comment by bootstraponline** [comment]
closing in favor of https://github.com/google/EarlGrey/pull/761

**Pull request closed without merging**
